  # Kafka producer for enriched packets (realtime)
  - id: "boltConfig-realtime-topic-%projectId%"
    className: "org.apache.storm.kafka.bolt.selector.DefaultTopicSelector"
    constructorArgs:
      - "streaming.realtime.%projectId%"